### ISSUE TITLE
Why hybrid language, not Python with type annotations?

### ISSUE THREAD

**Issue by denfromufa** [nicolasessisbreton/fython#3]
Why hybrid language, not Python with type annotations? E.g. like Cython, numba, pythran?

**Comment by nicolasessisbreton** [comment]
One of the great point in Python is its clean syntax.
I wanted this to transpire to Fython, so that even the definition of an involved type like
    real(c_float) dimension(:, :, :) allocatable contiguous x

is perfectly readable and the intention is understood at a glimpse.

With a type annotation system, this would be
  x = Real(kind=c_float, dimension=[a, a, a], pointer=1, allocatable=1)

The colon is invalid syntax in Python so, something else must be used (above 'a' for assumed).
You can see the problem. That just for elementary type. For higher objects such as function and class, annotations will turn take them away from Python clarity principle.
